### ISSUE TITLE
'view.context' not registered on Container

### ISSUE THREAD

**Issue by pikturdev** [dry-rb/dry-web-roda#55]
Steps to reproduce

Run generator `dry-web-roda new my_app --arch=flat`

Per #54, fix gem incompatibility issue
```
# Gemfile
gem 'rouge', '2.1.1'
# ...
```

```
$ bundle
$ bundle exec shotgun -p 3001 -o 0.0.0.0 config.ru
$ open http://localhost:3001
```

This is because `'view.context'` is not registered with the Container. The key is referenced during boot
[Controller.config.context](https://github.com/dry-rb/dry-web-roda/blob/master/lib/dry/web/roda/templates/view_controller.rb.tt#L12) and during response rendering [Roda::RodaPlugins::DryView](https://github.com/dry-rb/dry-web-roda/blob/master/lib/roda/plugins/dry_view.rb#L12)

```
Boot Error

Dry::System::InvalidComponentError: Tried to create an invalid "view.context" component - namespace +my_app+ not found in path

gems/dry-system-0.7.3/lib/dry/system/component.rb:70:in `remove_namespace_from_path'
gems/dry-system-0.7.3/lib/dry/system/component.rb:62:in `extract_identifier'
gems/dry-system-0.7.3/lib/dry/system/component.rb:50:in `block in new'
gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
gems/dry-system-0.7.3/lib/dry/system/component.rb:45:in `new'
gems/dry-system-0.7.3/lib/dry/system/container.rb:480:in `component'
gems/dry-system-0.7.3/lib/dry/system/container.rb:506:in `load_component'
gems/dry-system-0.7.3/lib/dry/system/container.rb:448:in `resolve'
gems/dry-container-0.6.0/lib/dry/container/mixin.rb:125:in `[]'
my_app/lib/my_app/view/controller.rb:13:in `block in <class:Controller>'
gems/dry-configurable-0.7.0/lib/dry/configurable.rb:70:in `configure'
my_app/lib/my_app/view/controller.rb:11:in `<class:Controller>'
my_app/lib/my_app/view/controller.rb:10:in `<module:View>'
my_app/lib/my_app/view/controller.rb:9:in `<module:MyApp>'
my_app/lib/my_app/view/controller.rb:8:in `<top (required)>'
my_app/lib/my_app/views/welcome.rb:1:in `require'
my_app/lib/my_app/views/welcome.rb:1:in `<top (required)>'
gems/dry-system-0.7.3/lib/dry/system/container.rb:497:in `require'
gems/dry-system-0.7.3/lib/dry/system/container.rb:497:in `require_component'
gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:37:in `block in call'
gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:34:in `each'
gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:34:in `call'
gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:27:in `block in finalize!'
gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:27:in `each'
gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:27:in `finalize!'
gems/dry-system-0.7.3/lib/dry/system/container.rb:263:in `finalize!'
my_app/system/boot.rb:8:in `<top (required)>'
config.ru:1:in `require_relative'
config.ru:1:in `block in inner_app'
gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `inner_app'
gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `eval'
gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `inner_app'
gems/shotgun-0.9.2/lib/shotgun/loader.rb:103:in `assemble_app'
gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
gems/shotgun-0.9.2/lib/shotgun/favicon.rb:12:in `call'
gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'
gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Registering the namespace resolves the issue**

```
# system/boot/view.rb
MyApp::Container.namespace 'view' do |container|
  container.finalize :view do
    init do
      require 'my_app/view/context'
    end

    start do
      container.register 'context', MyApp::View::Context.new
    end
  end
end
```

Is `dry-web-roda` ready for use?

**Comment by timriley** [comment]
Thanks for reporting this, I'll be able to check this out and make a release with a fix next week. 

dry-web-roda is certainly beta software, as you can see, but it is in use and working fine in production. The app generation side of things is the part that's undergoing to most change right now, which is why bugs like this have crept in. Sorry for the inconvenience, but I appreciate you sharing the problems!

**Comment by pikturdev** [comment]
I appreciate your swift response and understand the situation. I'll continue to work through and report any issues I encounter. Loving what you guys are doing with the Dry suite and ROM. Keep up the good work.

**Comment by pikturdev** [comment]
The solution is actually much simpler. Simply invert the "magic comment" from `# auto_register: false` to `true` [ref](https://github.com/dry-rb/dry-web-roda/blob/master/lib/dry/web/roda/templates/view_context.rb.tt#L1)
