### ISSUE TITLE
Version 0.7.5 crashes with dry-system 0.7.3

### ISSUE THREAD

**Issue by alejandrobabio** [dry-rb/dry-web-roda#61]
If I created a new umbrella app, started the server and visited `localhost:3000`. Then I got this output:

```
Something went wrong while loading config.ru

Dry::System::InvalidComponentError: Tried to create an invalid "view.context" component - namespace +main+ not found in path

/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/component.rb:70:in `remove_namespace_from_path'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/component.rb:62:in `extract_identifier'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/component.rb:50:in `block in new'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/component.rb:45:in `new'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/container.rb:480:in `component'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/container.rb:506:in `load_component'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/container.rb:448:in `resolve'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-container-0.6.0/lib/dry/container/mixin.rb:125:in `[]'
/home/alejandro/source/learn/dry-rb/todo/apps/main/lib/main/view/controller.rb:12:in `block in <class:Controller>'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-configurable-0.7.0/lib/dry/configurable.rb:70:in `configure'
/home/alejandro/source/learn/dry-rb/todo/apps/main/lib/main/view/controller.rb:10:in `<class:Controller>'
/home/alejandro/source/learn/dry-rb/todo/apps/main/lib/main/view/controller.rb:9:in `<module:View>'
/home/alejandro/source/learn/dry-rb/todo/apps/main/lib/main/view/controller.rb:8:in `<module:Main>'
/home/alejandro/source/learn/dry-rb/todo/apps/main/lib/main/view/controller.rb:7:in `<top (required)>'
/home/alejandro/source/learn/dry-rb/todo/apps/main/lib/main/views/welcome.rb:1:in `require'
/home/alejandro/source/learn/dry-rb/todo/apps/main/lib/main/views/welcome.rb:1:in `<top (required)>'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/container.rb:497:in `require'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/container.rb:497:in `require_component'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:37:in `block in call'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:34:in `each'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:34:in `call'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:27:in `block in finalize!'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:27:in `each'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/auto_registrar.rb:27:in `finalize!'
/home/alejandro/.rvm/gems/ruby-2.3.3@dwr75/gems/dry-system-0.7.3/lib/dry/system/container.rb:263:in `finalize!'
/home/alejandro/source/learn/dry-rb/todo/apps/main/system/boot.rb:3:in `<top (required)>'
```
In the app in `apps/main/system/boot.rb:3` calls `Main::Container.finalize!` and after that in `apps/main/lib/main/view/controller.rb:12` it sets the `config.context`.

```ruby
# auto_register: false

require "slim"
require "dry-view"
require "main/container"

module Main
  module View
    class Controller < Dry::View::Controller
      configure do |config|
        config.paths = [Container.root.join("web/templates")]
        config.context = Container["view.context"]
        config.layout = "application"
      end
    end
  end
end
```

I found 2 workarounds in order to make the app work.

1) Change in the Gemfile `gem "dry-system", ">= 0.7.1"` with `gem "dry-system", "0.7.1"` and `bundle update dry-system`

2) Change the `Main::View::Controller` and setting the `context` as an injected dependency instead as a config value. This way: 

```ruby
# auto_register: false

require "slim"
require "dry-view"
require "main/container"
require "main/import"

module Main
  module View
    class Controller < Dry::View::Controller
      include Import["view.context"]

      configure do |config|
        config.paths = [Container.root.join("web/templates")]
        config.layout = "application"
      end
    end
  end
end
``` 

I guess the first one could be a fix for that and the second something to think about.

Thank you for the awesome job that you are doing with the dry-rb gems.

**Comment by timriley** [comment]
You're right, this was a bug in dry-system that got fixed in 0.8.0, which we now use as of #64, so I think we can call this fixed too.
