### ISSUE TITLE
cannot load such file -- sequel with rackup

### ISSUE THREAD

**Issue by deepj** [dry-rb/dry-web-roda#79]
This happens with new freshly generated application. It looks a bug to me.

How to reproduce:

1. `dry-web-roda new test_app`
2. `cd test_app`
3. `bundle install`
4. `rake db:create`
5. `rackup`

I got:

```
Traceback (most recent call last):
	42: from ~/.gem/ruby/2.5.0/bin/rackup:23:in `<main>'
	41: from ~/.gem/ruby/2.5.0/bin/rackup:23:in `load'
	40: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	39: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	38: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:283:in `start'
	37: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
	36: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
	35: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	34: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
	33: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
	32: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
	31: from ~/dev/pokus/test_app/config.ru:in `<main>'
	30: from ~/dev/pokus/test_app/config.ru:in `new'
	29: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
	28: from ~/.gem/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
	27: from ~/dev/pokus/test_app/config.ru:1:in `block in <main>'
	26: from ~/dev/pokus/test_app/config.ru:1:in `require_relative'
	25: from ~/dev/pokus/test_app/system/boot.rb:8:in `<top (required)>'
	24: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/container.rb:298:in `finalize!'
	23: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:65:in `finalize!'
	22: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter/component_registry.rb:14:in `each'
	21: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter/component_registry.rb:14:in `each'
	20: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:66:in `block in finalize!'
	19: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:86:in `start'
	18: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:130:in `with_component'
	17: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:89:in `block in start'
	16: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:74:in `init'
	15: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:130:in `with_component'
	14: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:75:in `block in init'
	13: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:101:in `call'
	12: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:130:in `with_component'
	11: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:106:in `block in call'
	10: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/booter.rb:76:in `block (2 levels) in init'
	 9: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/components/bootable.rb:85:in `init'
	 8: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:54:in `call'
	 7: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:54:in `each'
	 6: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:56:in `block in call'
	 5: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:79:in `init'
	 4: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:119:in `trigger!'
	 3: from ~/dev/pokus/test_app/system/boot/persistence.rb:3:in `block (2 levels) in <top (required)>'
	 2: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:132:in `method_missing'
	 1: from ~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:132:in `public_send'
~/.gem/ruby/2.5.0/gems/dry-system-0.9.2/lib/dry/system/lifecycle.rb:132:in `require': cannot load such file -- sequel (LoadError)
```

`sequel` is in `Gemfile` btw.

I would expect I can run the application with `rackup` command without throwing exceptions.

**Comment by solnic** [comment]
You probably want to do `bundle exec rackup`

**Comment by victormartins** [comment]
This was also happening to me running :
`shotgun -p 3000 -o 0.0.0.0 config.ru`

Running using bundle (like it says in the README) solved the problem as well.
`bundle exec shotgun -p 3000 -o 0.0.0.0 config.ru`

Thank you for this project guys, I'm really excited to try this out.

**Comment by deepj** [comment]
@solnic Personally, I guess there wouldn't be a need to require `bundle exec` if my environment is not in a collision with some other versions of my dependencies.

I'm not sure, but requiring `bundle exec` seems to be not right.

**Comment by solnic** [comment]
@deepj I just checked, it works for me. So I expect your environment is borked.

**Comment by timriley** [comment]
@deepj Right now, `bundle exec` is required to invoke whatever command you use to boot the app. I'll fix this by adding a `require "bundler/setup"` to `system/boot.rb`.

**Comment by deepj** [comment]
@timriley Yes, thanks. It was also my fix in the end. Sorry for being late to answer. But I'm happy this was resolved.

**Comment by dawidof** [comment]
`gem 'sequel_pg', require: 'sequel'`
