### ISSUE TITLE
Name error on fresh install

### ISSUE THREAD

**Issue by whysthatso** [dry-rb/dry-web-roda#90]
dry-web-roda: 0.11.0
ruby: 2.5.3 and 2.4.5

steps:
1. gem install bundler
1. gem install dry-web-roda
1. dry-web-roda new project
1. cd project
1. bundle install
1. rake db:create

i've been trying to get a freshly generated project going but instantly ran into this:

```
rake aborted!
NameError: uninitialized constant Dry::Monitor::Rack
Did you mean?  Rake
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dry-web-0.8.0/lib/dry/web/container.rb:25:in `register_rack_monitor'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dry-web-0.8.0/lib/dry/web/container.rb:16:in `block in inherited'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dry-system-0.9.2/lib/dry/system/container.rb:105:in `instance_eval'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dry-system-0.9.2/lib/dry/system/container.rb:105:in `block in configure'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dry-system-0.9.2/lib/dry/system/container.rb:105:in `each'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dry-system-0.9.2/lib/dry/system/container.rb:105:in `configure'
/home/user/projects/dry-rb/wellpress-crm/system/wellpress_crm/container.rb:6:in `<class:Container>'
/home/user/projects/dry-rb/wellpress-crm/system/wellpress_crm/container.rb:5:in `<module:WellpressCrm>'
/home/user/projects/dry-rb/wellpress-crm/system/wellpress_crm/container.rb:4:in `<top (required)>'
/home/user/projects/dry-rb/wellpress-crm/Rakefile:5:in `require_relative'
/home/user/projects/dry-rb/wellpress-crm/Rakefile:5:in `<top (required)>'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
bin/rake:29:in `load'
bin/rake:29:in `<main>'
```

**Comment by waiting-for-dev** [comment]
Surely https://github.com/dry-rb/dry-web/issues/45 can help you

**Comment by whysthatso** [comment]
thanks.
however, i will close it as i just read on the discourse site that this project is due to be retired anyway. will move on to hanami.
